export const imgs = {
  bg: {
    instance: new Image(),
    path: "img/base.png",
  },
  numbers: [
    { instance: new Image(), path: "img/1.png" },
    { instance: new Image(), path: "img/2.png" },
    { instance: new Image(), path: "img/3.png" },
    { instance: new Image(), path: "img/4.png" },
    { instance: new Image(), path: "img/5.png" },
    { instance: new Image(), path: "img/6.png" },
    { instance: new Image(), path: "img/7.png" },
    { instance: new Image(), path: "img/8.png" },
    { instance: new Image(), path: "img/9.png" },
    { instance: new Image(), path: "img/10.png" },
    { instance: new Image(), path: "img/11.png" },
    { instance: new Image(), path: "img/12.png" },
    { instance: new Image(), path: "img/13.png" },
    { instance: new Image(), path: "img/14.png" },
    { instance: new Image(), path: "img/15.png" },
    { instance: new Image(), path: "img/16.png" },
    { instance: new Image(), path: "img/17.png" },
    { instance: new Image(), path: "img/18.png" },
    { instance: new Image(), path: "img/19.png" },
    { instance: new Image(), path: "img/20.png" },
  ],
  frameAnim: {
    instance: new Image(),
    path: "img/kira_sprites.png",
  },
} as const;
export const se = {
  numbers: [
    new Audio("se/1.mp3"),
    new Audio("se/2.mp3"),
    new Audio("se/3.mp3"),
    new Audio("se/4.mp3"),
    new Audio("se/5.mp3"),
    new Audio("se/6.mp3"),
    new Audio("se/7.mp3"),
    new Audio("se/8.mp3"),
    new Audio("se/9.mp3"),
    new Audio("se/10.mp3"),
    new Audio("se/11.mp3"),
    new Audio("se/12.mp3"),
    new Audio("se/13.mp3"),
    new Audio("se/14.mp3"),
    new Audio("se/15.mp3"),
    new Audio("se/16.mp3"),
    new Audio("se/17.mp3"),
    new Audio("se/18.mp3"),
    new Audio("se/19.mp3"),
    new Audio("se/20.mp3"),
  ],
  clear: new Audio("se/clear.mp3"),
  fail: new Audio("se/fail.mp3"),
} as const;
